CATS2TANGO = {
    # STATE PARAMS core.state_params
    'POWER_1_0': 'Powered',
    'AUTO_MODE_STATUS_1_0': 'AutoMode',
    'DEFAULT_STATUS_1_0': 'DefaultStatus',
    'TOOL_NUM_OR_NAME': 'Tool',
    'PATH_NAME': 'Path',
    'LID_NUM_SAMPLE_MOUNTED_ON_TOOL': 'LidSampleOnTool',
    'NUM_SAMPLE_ON_TOOL': 'NumSampleOnTool',
    'PUCK_NUM_SAMPLE_MOUNTED_ON_TOOL': 'PuckNumberOnTool',
    'PUCK_NUM_SAMPLE_MOUNTED_ON_TOOL2': 'PuckNumberOnTool2',
    'NUM_SAMPLE_ON_TOOL2': 'NumSampleOnTool2',
    'LID_NUM_SAMPLE_MOUNTED_ON_DIFFRACTOMETER': 'LidSampleOnDiff',
    'PUCK_NUM_SAMPLE_MOUNTED_ON_DIFFRACTOMETER': 'PuckSampleOnDiff',
    'NUM_SAMPLE_MOUNTED_ON_DIFFRACTOMETER': 'NumSampleOnDiff',
    'NUM_OF_PLATE_ON_TOOL': 'NumPlateOnTool',
    'WELL_NUM': 'Well',
    'BARCODE_NUM': 'Barcode',
    'PATH_RUNNING_1_0': 'PathRunning',
    'LN2_REGULATION_RUNNING_1_0': 'LN2Regulating',
    'LN2_WARMING_RUNNING_1_0': 'LN2Warming',
    'ROBOT_SPEED_RATIO': 'SpeedRatio',
    'PUCK_DET_RESULT_DEW1': 'PuckDetectionDewar1',
    'PUCK_DET_RESULT_DEW2': 'PuckDetectionDewar2',
    'POSITION_NUM_DEW1': 'PositionNumberDewar1',
    'POSITION_NUM_DEW2': 'PositionNumberDewar2',
    'LID_NUM_SAMPLE_MOUNTED_ON_TOOL2': 'PuckNumberInTool2',
    'NUM_SAMPLE_ON_TOOL2': 'SampleNumberInTool2',
    'CURR_NUM_SOAKING': 'CurrentNumberOfSoaking',
    'PUCK_TYPE_LID1': 'PuckTypeLid1',
    'PUCK_TYPE_LID2': 'PuckTypeLid2',
    'PUCK_TYPE_LID3': 'PuckTypeLid3',
    'PUCK_TYPE_LID': 'PuckTypeLid',

    # DI PARAMS core.di_params
    'CRYOGEN_SENSORS_OK': 'di_CryoOK',
    'ESTOP_AND_AIRPRES_OK': 'di_EStopAirpresOK',
    'COLLISION_SENSOR_OK': 'di_CollisonSensorOK',
    'CRYOGEN_HIGH_LEVEL_ALARM': 'di_CryoHighLevelAlarm',
    'CRYOGEN_HIGH_LEVEL': 'di_CryoHighLevel',
    'CRYOGEN_LOW_LEVEL': 'di_CryoLowLevel',
    'CRYOGEN_LOW_LEVEL_ALARM': 'di_CryoLowLevelAlarm',
    'CRYOGEN_LIQUID_DETECTION': 'di_CryoLiquidDetection',
    'PRI_GFM': 'di_PRI_GFM',
    'PRI_API': 'di_PRI_API',
    'PRI_APL': 'di_PRI_APL',
    'PRI_SOM': 'di_PRI_SOM',
    'PLATE_ON_DIFF': 'di_PlateOnDiff',  # ISARA
    'DIFF_PLATE_MODE': 'di_DiffPlateMode',  # ISARA
    'CASSETTE_1_PRESENCE': 'di_Cassette1Presence',
    'CASSETTE_2_PRESENCE': 'di_Cassette2Presence',
    'CASSETTE_3_PRESENCE': 'di_Cassette3Presence',
    'CASSETTE_4_PRESENCE': 'di_Cassette4Presence',
    'CASSETTE_5_PRESENCE': 'di_Cassette5Presence',
    'CASSETTE_6_PRESENCE': 'di_Cassette6Presence',
    'CASSETTE_7_PRESENCE': 'di_Cassette7Presence',
    'CASSETTE_8_PRESENCE': 'di_Cassette8Presence',
    'CASSETTE_9_PRESENCE': 'di_Cassette9Presence',
    'LID_1_OPENED': 'di_Lid1Open',
    'LID_2_OPENED': 'di_Lid2Open',
    'LID_3_OPENED': 'di_Lid3Open',
    'TOOL_OPENED': 'di_ToolOpen',
    'TOOL_CLOSED': 'di_ToolClosed',
    'LIMSW1_ROT_GRIP_AXIS': 'di_LimSW1RotGripAxis',
    'LIMSW2_ROT_GRIP_AXIS': 'di_LimSW2RotGripAxis',
    'MODBUS_PLC_LIFE_BIT': 'di_ModbusPLCLifeBit',
    'LIFE_BIT_COMING_FROM_PLC': 'di_LifeBitFromPLC',
    'ACTIVE_LID_OPENED': 'di_ActiveLidOpened',
    'NEW_ACTIVE_LID_OPENED': 'di_NewActiveLidOpened',
    'TOOL_CHANGER_OPENED': 'di_ToolChangerOpened',
    'ACTIVE_CASSETTE_PRESENCE': 'di_ActiveCassettePresence',
    'NEW_ACTIVE_CASSETTE_PRESENCE': 'di_NewActiveCassettePresence',
    'ALL_LIDS_CLOSED': 'di_AllLidsClosed',
    'PROCESS_INPUT_5': 'di_PRI5',
    'PROCESS_INPUT_6': 'di_PRI6',
    'PROCESS_INPUT_7': 'di_PRI7',
    'PROCESS_INPUT_8': 'di_PRI8',
    'PROCESS_INPUT_9': 'di_PRI9',
    'PROCESS_INPUT_10': 'di_PRI10',
    'PROCESS_INPUT_11': 'di_PRI11',
    'PROCESS_INPUT_12': 'di_PRI12',
    'VIRTUAL_INPUT_90': 'di_VI90',
    'VIRTUAL_INPUT_91': 'di_VI91',
    'VIRTUAL_INPUT_92': 'di_VI92',
    'VIRTUAL_INPUT_93': 'di_VI93',
    'VIRTUAL_INPUT_94': 'di_VI94',
    'VIRTUAL_INPUT_95': 'di_VI95',
    'VIRTUAL_INPUT_96': 'di_VI96',
    'VIRTUAL_INPUT_97': 'di_VI97',
    'VIRTUAL_INPUT_98': 'di_VI98',
    'VIRTUAL_INPUT_99': 'di_VI99',

    # DO PARAMS core.do_params
    'TOOL_CHANGER': 'do_ToolChanger',
    'TOOL_OPEN_CLOSE': 'do_ToolOpenClose',
    'FAST_OUTPUT': 'do_FastOutput',
    'PRO1_MON': 'do_PRO1_MON',
    'PRO2_COL': 'do_PRO2_COL',
    'PRO3_LNW': 'do_PRO3_LNW',
    'PRO4_LNA': 'do_PRO4_LNA',
    'GREEN_LIGHT': 'do_GreenLight',
    'PILZ_RELAY_RESET': 'do_PilzRelayReset',
    'SERVO_CARD_ON': 'do_ServoCardOn',
    'SERVO_CARD_ROTATION_+-': 'do_ServoCardRotation',
    'CRYOGEN_VALVE_LN2_C': 'do_CryoValveLN2C',
    'CRYOGEN_VALVE_LN2_E': 'do_CryoValveLN2E',
    'CRYOGEN_VALVE_GN2_E': 'do_CryoValveGN2E',
    'HEATER_ON_OFF': 'do_HeaterOnOff',
    'OPEN_CLOSE_LID_1_1': 'do_OpenCloseLid11',
    'OPEN_CLOSE_LID_1_2': 'do_OpenCloseLid12',
    'OPEN_CLOSE_LID_2_1': 'do_OpenCloseLid21',
    'OPEN_CLOSE_LID_2_2': 'do_OpenCloseLid22',
    'OPEN_CLOSE_LID_3_1': 'do_OpenCloseLid31',
    'OPEN_CLOSE_LID_3_2': 'do_OpenCloseLid32',
    'REQ_DEW1_POS_B1': 'do_RequestDew1PosBit1',
    'REQ_DEW1_POS_B2': 'do_RequestDew1PosBit2',
    'REQ_DEW1_POS_B3': 'do_RequestDew1PosBit3',
    'REQ_DEW1_POS_B4': 'do_RequestDew1PosBit4',
    'OPEN_LID': 'do_OpenLid',
    'CLOSE_LID': 'do_CloseLid',
    'OPEN_NEW_LID': 'do_OpenNewLid',
    'CLOSE_NEW_LID': 'do_CloseNewLid',
    'BARCODE_READER_CONTROL': 'do_BarcodeReader',
    'CLOSE_ALL_LIDS': 'do_CloseAllLids',
    'PRO5_IDL': 'do_PRO5_IDL',
    'PRO6_RAH': 'do_PRO6_RAH',
    'PRO7_RI1': 'do_PRO7_RI1',
    'PRO8_RI2': 'do_PRO8_RI2',
    'PRO9_LIO': 'do_PRO9_LIO',
    'PROCESS_OUTPUT_10': 'do_PRO10',
    'PROCESS_OUTPUT_11': 'do_PRO11',
    'PROCESS_OUTPUT_12': 'do_PRO12',
    'REQ_DEW2_POS_B1': 'do_RequestDew2PosBit1',
    'REQ_DEW2_POS_B2': 'do_RequestDew2PosBit2',
    'REQ_DEW2_POS_B3': 'do_RequestDew2PosBit3',
    'REQ_DEW2_POS_B4': 'do_RequestDew2PosBit4',
    'CRYO_VALVE_LN2_C_DEW2': 'do_CryoValveLN2CDew2',
    'CRYO_VALVE_LN2_E_DEW2': 'do_CryoValveLN2EDew2',
    'CRYO_VALVE_GN2_E_DEW2': 'do_CryoVavleGN2EDew2',
    'OPEN_CLOSE_LID_3_1_DEW2': 'do_OpenCloseLid31Dew2',
    'OPEN_CLOSE_LID_3_2_DEW2': 'do_OpenCloseLid32Dew2',
    'OPEN_CLOSE_LID_4_1_DEW2': 'do_OpenCloseLid41Dew2',
    'OPEN_CLOSE_LID_4_2_DEW2': 'do_OpenCloseLid42Dew2',
    'PROCESS_OUTPUT_13': 'do_PRO13',
    'PROCESS_OUTPUT_14': 'do_PRO14',
    'PROCESS_OUTPUT_15': 'do_PRO15',
    'PROCESS_OUTPUT_16': 'do_PRO16',
    'ROT_DEW_NEW_POS_CTRL_ROBOT_WORKING': 'do_RotationDewNewPosWorking',
    'ROT_DEW_POS_CTRL_CASS_LOADING': 'do_RotationDewarPosCassLoading',
    'ROT_DEW_POS_CTRL_ROBOT_WORKING': 'do_RotationDewPosWorking',

    # POSITION PARAMS core.position_params
    'X_POSITION_IN_MM': 'Xpos',
    'Y_POSITION_IN_MM': 'Ypos',
    'Z_POSITION_IN_MM': 'Zpos',
    'RX_POSITION_IN_MM': 'RXpos',
    'RY_POSITION_IN_MM': 'RYpos',
    'RZ_POSITION_IN_MM': 'RZpos',

    # MESSAGE
    'MESSAGE': 'Message'
}

TANGO2CATS = {}
for k, v in CATS2TANGO.items():
    TANGO2CATS[v] = k
